# Starter pipeline
- task: ArtifactoryGenericDownload@3
  inputs:
    connection: 'basic-nitaym'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "maven-remote-smart",
            "build": "my-build,1.0.0"
            "target": "/test"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    failNoOp: true
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
